# NumPy 

NumPy (or Numpy) is a Linear Algebra Library for Python, the reason it is so important for Data Science with Python is that almost all of the libraries in the PyData Ecosystem rely on NumPy as one of their main building blocks.

## Installation

    
    conda install numpy

## Using NumPy

Once you've installed NumPy you can import it as a library:

In [6]:
import numpy as np

Numpy has many built-in functions and capabilities. Important aspects of Numpy: vectors,arrays,matrices, and number generation. 

# Numpy Arrays

NumPy arrays are the main way we will use Numpy throughout the course. Numpy arrays essentially come in two flavors: vectors and matrices. Vectors are strictly 1-d arrays and matrices are 2-d (but you should note a matrix can still have only one row or one column).

## Creating NumPy Arrays

### From a Python List

We can create an array by directly converting a list or list of lists:

In [4]:
list_1 = [1,2,3]
list_1

[1, 2, 3]

In [7]:
np.array(my_list)

array([1, 2, 3])

In [8]:
matrix_1 = [[1,2,3],[4,5,6],[7,8,9]]
matrix_1

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [9]:
np.array(matrix_1)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

## Built-in Methods

### arange

Return evenly spaced values within a given interval.

In [10]:
np.arange(0,15)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [11]:
np.arange(0,12,2)

array([ 0,  2,  4,  6,  8, 10])

### zeros and ones

Generate arrays of zeros or ones

In [12]:
np.zeros(4)

array([0., 0., 0., 0.])

In [14]:
np.zeros((6,6))

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [15]:
np.ones(2)

array([1., 1.])

In [16]:
np.ones((3,2))

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

### linspace
Return evenly spaced numbers over a specified interval.

In [17]:
np.linspace(0,10,4)

array([ 0.        ,  3.33333333,  6.66666667, 10.        ])

In [18]:
np.linspace(0,10,40)

array([ 0.        ,  0.25641026,  0.51282051,  0.76923077,  1.02564103,
        1.28205128,  1.53846154,  1.79487179,  2.05128205,  2.30769231,
        2.56410256,  2.82051282,  3.07692308,  3.33333333,  3.58974359,
        3.84615385,  4.1025641 ,  4.35897436,  4.61538462,  4.87179487,
        5.12820513,  5.38461538,  5.64102564,  5.8974359 ,  6.15384615,
        6.41025641,  6.66666667,  6.92307692,  7.17948718,  7.43589744,
        7.69230769,  7.94871795,  8.20512821,  8.46153846,  8.71794872,
        8.97435897,  9.23076923,  9.48717949,  9.74358974, 10.        ])

## eye

Creates an identity matrix

In [19]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

## Random 

Numpy also has lots of ways to create random number arrays:

### rand
Creating an array of the given shape and populate it with
random samples from a uniform distribution
over ``[0, 1)``.

In [20]:
np.random.rand(4)

array([0.90576308, 0.13445437, 0.26447239, 0.86132233])

In [22]:
np.random.rand(4,4)

array([[0.31700998, 0.68542722, 0.9100988 , 0.18603533],
       [0.90305804, 0.29733267, 0.77883677, 0.55445775],
       [0.83686667, 0.07376481, 0.29229944, 0.81024178],
       [0.25771251, 0.46132998, 0.90669192, 0.86761089]])

### randn

Return a sample (or samples) from the "standard normal" distribution. Unlike rand which is uniform:

In [23]:
np.random.randn(4)

array([ 0.93907627,  0.36650371, -1.06734887,  0.35039851])

In [24]:
np.random.randn(5,5)

array([[-0.72842555, -0.51716961, -0.23589847,  0.75332974,  1.01745997],
       [-1.12756475, -1.0774895 , -1.76861686,  0.25257122, -0.00323184],
       [ 0.38617823, -0.52540789,  0.73492568, -0.13465723, -0.40205696],
       [-1.94338283, -0.22923303,  0.91327173, -0.73816692, -0.1175157 ],
       [-0.41073012, -0.49109808, -0.95247886,  0.28349798,  1.53250602]])

### randint
Return random integers from `low` (inclusive) to `high` (exclusive).

In [25]:
np.random.randint(1,1000)

151

In [27]:
np.random.randint(1,500,10)

array([ 29, 260,  75, 452, 122, 499, 107,  60,  88,  56])

## Array Attributes and Methods

In [56]:
arr_1 = np.arange(36)
arr_2 = np.random.randint(0,50,36)

In [58]:
arr_1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35])

In [59]:
arr_2

array([16, 19, 29, 27,  9, 28, 10,  5, 28,  9, 35, 43, 16, 20, 32, 29, 34,
       11,  7, 26, 22, 39, 34, 40, 42, 32, 27, 38, 14, 21, 49, 48, 23, 33,
        8, 29])

## Reshape
Returns an array containing the same data with a new shape.

In [60]:
arr_1.reshape(6,6)

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35]])

### max,min,argmax,argmin

These are useful methods for finding max or min values. Or to find their index locations using argmin or argmax

In [61]:
arr_2

array([16, 19, 29, 27,  9, 28, 10,  5, 28,  9, 35, 43, 16, 20, 32, 29, 34,
       11,  7, 26, 22, 39, 34, 40, 42, 32, 27, 38, 14, 21, 49, 48, 23, 33,
        8, 29])

In [62]:
arr_2.max()

49

In [63]:
arr_2.argmax()

30

In [65]:
arr_2.min()

5

In [66]:
arr_2.argmin()

7

## Shape

Shape is an attribute that arrays have (not a method):

In [67]:
# Vector
arr_1.shape

(36,)

In [69]:
# Notice the two sets of brackets
arr_2.reshape(6,6)

array([[16, 19, 29, 27,  9, 28],
       [10,  5, 28,  9, 35, 43],
       [16, 20, 32, 29, 34, 11],
       [ 7, 26, 22, 39, 34, 40],
       [42, 32, 27, 38, 14, 21],
       [49, 48, 23, 33,  8, 29]])

In [72]:
arr_1.reshape(4,9).shape

(4, 9)

In [79]:
arr_1.reshape(12,3)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17],
       [18, 19, 20],
       [21, 22, 23],
       [24, 25, 26],
       [27, 28, 29],
       [30, 31, 32],
       [33, 34, 35]])

In [81]:
arr_1.reshape(18,2).shape

(18, 2)

### dtype

You can also grab the data type of the object in the array:

In [82]:
arr_1.dtype

dtype('int32')

Thank you :)
